/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VistaController;
import Model.Producto;
import Conexion.Conexion;
import java.awt.List;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Model.Marca;
import Model.ProductoImportacion;
import Model.MarcaRepuesto;
import Model.TipoProducto;
import javax.swing.JOptionPane;
import Export.ExportarExcel;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicolas
 */
public class VistaImportacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaImportacion
     */DefaultTableModel model = new DefaultTableModel();
     ArrayList<ProductoImportacion> tablaImportacion = new ArrayList<>();
     ProductoImportacion nuevoProductoImportacion = new ProductoImportacion();
    public VistaImportacion() {
        
        
        
        
        initComponents();
       
        model.addColumn("REPUESTO");
        model.addColumn("MARCA VEHICULO");
        model.addColumn("MODELO");
        model.addColumn("MARCA REPUESTO");
        model.addColumn("CANTIDAD");
        llenarTabla();
        llenarCombo();
        

        
    }
    
    
    
    
   public void llenarTabla(){
   model.setRowCount(0);
   tbl_importacion.setModel(model);
   
    model.setRowCount(0);
    tbl_importacion.setModel(model);
    
        for (ProductoImportacion Importacion : tablaImportacion) {
            Object objeto [] = new Object[5];
            objeto [0] = Importacion.getRepuesto();
            objeto [1] = Importacion.getMarcaVehiculo();
            objeto [2] = Importacion.getModelo();
            objeto [3] = Importacion.getMarcaRepuesto();
            objeto [4] = Importacion.getCantidad();
            
            model.addRow(objeto);
        }
   
    }
    
    
    public void llenarCombo() {
    comboBox_NombreRepuesto.removeAllItems();
    comboBox_MarcaVehiculo.removeAllItems();
    comboBox_MarcaVehiculo.removeAllItems();

    comboBox_NombreRepuesto.addItem("");
    comboBox_MarcaVehiculo.addItem("");
    comboBox_MarcaVehiculo.addItem("");
    

    try {
        
        ArrayList<Marca> tablaMarca = Marca.buscarTodasMarcas();
        ArrayList<MarcaRepuesto> tablaMarcaRepuestos = MarcaRepuesto.buscarTodasMarcas();
        ArrayList<Producto> tablaProductos = Producto.buscarTodasMarcas();

        for (Producto producto : tablaProductos) {
            if (producto.getProducto_estado() == 0) {
                comboBox_NombreRepuesto.addItem(producto.getNombreProducto());
                
            }
        }

        for (Marca marca : tablaMarca) {
            comboBox_MarcaVehiculo.addItem(marca.getNombreMarca());
        }

        for (MarcaRepuesto marcaRepuesto : tablaMarcaRepuestos) {
            comboRepuesto.addItem(marcaRepuesto.getNombreMarca());
        }

      

    } catch (Exception e) {
        e.printStackTrace(); 
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboBox_MarcaVehiculo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboBox_NombreRepuesto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboRepuesto = new javax.swing.JComboBox<>();
        spinner_cantidad = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_importacion = new javax.swing.JTable();
        btn_CargarNuevaImportacion = new javax.swing.JButton();
        btn_eliminarImportacion = new javax.swing.JButton();
        btn_importarExcel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txt_modelos = new javax.swing.JTextField();
        comboBox_Elementos = new javax.swing.JComboBox<>();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel1.setText("PLANILLA DE IMPORTACION");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel2.setText("Repuesto a Importar");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel3.setText("Cantidad");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel4.setText("Marca Vehiculo");

        comboBox_NombreRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_NombreRepuestoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel5.setText("Marca Repuesto");

        tbl_importacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_importacion);

        btn_CargarNuevaImportacion.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        btn_CargarNuevaImportacion.setText("CARGAR");
        btn_CargarNuevaImportacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CargarNuevaImportacionActionPerformed(evt);
            }
        });

        btn_eliminarImportacion.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        btn_eliminarImportacion.setText("ELIMINAR DEL PEDIDO");
        btn_eliminarImportacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarImportacionActionPerformed(evt);
            }
        });

        btn_importarExcel.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        btn_importarExcel.setText("EXCEL");
        btn_importarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_importarExcelActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel7.setText("Modelo Vehiculo");

        txt_modelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_modelosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_modelos, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinner_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_importarExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(460, 460, 460))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_CargarNuevaImportacion, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboRepuesto, 0, 577, Short.MAX_VALUE)
                                    .addComponent(comboBox_MarcaVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboBox_NombreRepuesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_eliminarImportacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBox_Elementos, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox_NombreRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboBox_MarcaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(comboRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_modelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spinner_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CargarNuevaImportacion)
                    .addComponent(btn_importarExcel))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_eliminarImportacion)
                    .addComponent(comboBox_Elementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_modelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_modelosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_modelosActionPerformed

    private void btn_CargarNuevaImportacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CargarNuevaImportacionActionPerformed
 
        ProductoImportacion nuevoProductoImportacion = new ProductoImportacion();
        
        nuevoProductoImportacion.setRepuesto(comboBox_NombreRepuesto.getSelectedItem().toString());
        nuevoProductoImportacion.setMarcaVehiculo(comboBox_MarcaVehiculo.getSelectedItem().toString());
        nuevoProductoImportacion.setModelo(txt_modelos.getText().trim());
        nuevoProductoImportacion.setMarcaRepuesto(comboRepuesto.getSelectedItem().toString());
        int cantidad = (int) spinner_cantidad.getValue();
                
        nuevoProductoImportacion.setCantidad(cantidad);
        
        tablaImportacion.add(nuevoProductoImportacion);
        
        llenarTabla();
        llenarComboEliminar();
        







        
    }//GEN-LAST:event_btn_CargarNuevaImportacionActionPerformed

    private void comboBox_NombreRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_NombreRepuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_NombreRepuestoActionPerformed

    private void btn_importarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_importarExcelActionPerformed
       
                ExportarExcel obj;

try {
    obj = new ExportarExcel();
    obj.exportarExcel(tbl_importacion);
} catch (IOException ex) {
    System.out.println("Error: " + ex);
}
        
        
        
    }//GEN-LAST:event_btn_importarExcelActionPerformed

    private void btn_eliminarImportacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarImportacionActionPerformed
        
        
        for (ProductoImportacion productoImportacion : tablaImportacion) {
            String comparacion = productoImportacion.getRepuesto();
            if (comparacion.equals(comboBox_Elementos.getSelectedItem().toString())) {
              tablaImportacion.remove(productoImportacion);
                llenarTabla();
                llenarComboEliminar();
            }
            
        }
        
        
    }//GEN-LAST:event_btn_eliminarImportacionActionPerformed

     public void llenarComboEliminar(){
         comboBox_Elementos.removeAllItems();
     
         for (ProductoImportacion productoImportacion : tablaImportacion) {
             
             comboBox_Elementos.addItem(productoImportacion.getRepuesto());
             
         }
     
     }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CargarNuevaImportacion;
    private javax.swing.JButton btn_eliminarImportacion;
    private javax.swing.JButton btn_importarExcel;
    private javax.swing.JComboBox<String> comboBox_Elementos;
    private javax.swing.JComboBox<String> comboBox_MarcaVehiculo;
    private javax.swing.JComboBox<String> comboBox_NombreRepuesto;
    private javax.swing.JComboBox<String> comboRepuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner spinner_cantidad;
    private javax.swing.JTable tbl_importacion;
    private javax.swing.JTextField txt_modelos;
    // End of variables declaration//GEN-END:variables
}
