/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaController;
import Model.Usuario;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author nicolas
 */
public class VistaMain extends javax.swing.JFrame {

   
    JDesktopPane desktopPane = new JDesktopPane();
    
    
    
public VistaMain() {
    initComponents();
    
    // Configurar el JDesktopPane
    desktopPane.add(jPanel1);
    this.setContentPane(desktopPane);
    this.setTitle("Menu Principal");

    // Permitir redimensionar
    this.setResizable(true);  
    
    // Ajustar la ventana a pantalla completa
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);  // Expande la ventana a pantalla completa automáticamente

    // Quitar el límite máximo porque contradice la pantalla completa
    // this.setMaximumSize(new java.awt.Dimension(1400, 935));  // ⚠️ Eliminar esta línea
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        button1 = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 400));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/manin2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setAutoscrolls(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1428, 938);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -28, 1400, 938);

        jMenu1.setText("MENU PRINCIPAL");

        jMenuItem1.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jMenuItem1.setText("Ingreso Productos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jMenuItem3.setText("Importacion");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem7.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jMenuItem7.setText("Pedidos Mayoristas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem9.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jMenuItem9.setText("Cerrar Sesion");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("CONFIGURACIONES");

        jMenuItem4.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jMenuItem4.setText("Ingreso Marca");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jMenuItem5.setText("Ingreso Tipo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem10.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jMenuItem10.setText("Ingreso Marca Repuesto");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem2.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jMenuItem2.setText("Ingreso Proveedores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem8.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jMenuItem8.setText("Edicion Usuario");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("VISTA DE STOCK");

        jMenuItem6.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jMenuItem6.setText("Productos en Bodega");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
 
        VistaIngresos formVistaIngresos = new VistaIngresos();
        desktopPane.add(formVistaIngresos);
        formVistaIngresos.setVisible(true);
        

        
        
        


        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

VistaTipoRepuesto formVistaTipo = new VistaTipoRepuesto();
desktopPane.add(formVistaTipo);
formVistaTipo.setVisible(true);







    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        
        VistaBodega formBodega = new VistaBodega();
        desktopPane.add(formBodega);
        formBodega.setVisible(true);
        
        
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed


        
        VistaImportacion formiImportacion = new VistaImportacion();
        desktopPane.add(formiImportacion);
        formiImportacion.setVisible(true);





        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed



VistaIngresoMarca formIngresoMarca = new VistaIngresoMarca();
desktopPane.add(formIngresoMarca);
formIngresoMarca.setVisible(true);






    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed


VistaCaja formCaja = new VistaCaja();
desktopPane.add(formCaja);
formCaja.setVisible(true);







        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
       
       
        
       String usr = JOptionPane.showInputDialog(null, "USUARIO:");
       
        try {
                 boolean sucess = Usuario.verificacionAdmin(usr); 
                   
                   if (sucess) {
                       

VistaCrearUsuario formVistaCrearUsuario = new VistaCrearUsuario();
desktopPane.add(formVistaCrearUsuario);
formVistaCrearUsuario.setVisible(true);


            } else {
                       JOptionPane.showMessageDialog(this, "Usuario no posee permiso de Administrador.");
            }


        } catch (Exception e) {
        }







        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
       
        VistaLogin.visible();
        this.setVisible(false);
        this.dispose();
    
       
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        VistaMarcaRepuestos formMarcaRepuestos = new VistaMarcaRepuestos();
        desktopPane.add(formMarcaRepuestos);
        formMarcaRepuestos.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        VistaProveedor formvVistaProveedor = new VistaProveedor();
        desktopPane.add(formvVistaProveedor);
        formvVistaProveedor.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    
    

    

    
   /*
    public static void main(String[] args) {
       VistaMain vistaMain = new VistaMain();
   
      

 
               vistaMain.setVisible(true);

               
    }
    
    
    */

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
