/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VistaController;

import Model.TipoProducto;
import Controller.TipoRepuestoController;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author nicolas
 */
public class VistaTipoRepuesto extends javax.swing.JInternalFrame {

    DefaultTableModel model = new DefaultTableModel();
    
    public VistaTipoRepuesto() {
        initComponents();
        
        model.addColumn("Tipo de Repuesto");
        model.addColumn("Codigo (ID Producto)");
        llenarTabla();
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_tipoRepuesto = new javax.swing.JTable();
        txt_tipoRepuesto = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        combo_todoTipo = new javax.swing.JComboBox<>();
        btn_eliminar = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel1.setText("INGRESO TIPO DE PRODUCTOS");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel2.setText("Nuevo Tipo de Producto :");

        tabla_tipoRepuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_tipoRepuesto);

        btn_agregar.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_modificar.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel3.setText("Seleccionar :");

        combo_todoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_todoTipoActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_tipoRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(combo_todoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combo_todoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modificar)
                    .addComponent(btn_eliminar))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(txt_tipoRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
         
         String nombreTipo = txt_tipoRepuesto.getText().trim();
         TipoRepuestoController tipoRepuestoController = new TipoRepuestoController();
         
        try {
           
            if (!nombreTipo.isEmpty()&&!TipoProducto.verificarIngreso(nombreTipo)) {
                boolean evento = tipoRepuestoController.ingresoTipoProducto(nombreTipo);
           

                
                JOptionPane.showMessageDialog(this, "Tipo de producto ingresado correctamente");

            }
          
            
            else{
            
             JOptionPane.showMessageDialog(this, "Debe completar campos con datos no duplicados");
            
            }
           
          
           
            
        } catch (Exception e) {
           
            JOptionPane.showMessageDialog(this, "No se pudo conectar con base de datos problema en el paquete TipoPorductoVistaController ");
        }
        
        txt_tipoRepuesto.setText("");
        llenarCombo();
        llenarTabla();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void combo_todoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_todoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_todoTipoActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        
        String verificacioVacio = txt_tipoRepuesto.getText();
        
        if (!verificacioVacio.isEmpty()&&!TipoProducto.verificarIngreso(verificacioVacio)) {
        
            try {
        TipoRepuestoController tipoRepuestoController = new TipoRepuestoController();
        int id_tipo = Integer.parseInt(combo_todoTipo.getSelectedItem().toString());
        String nombreNuevo = txt_tipoRepuesto.getText().trim();
        
        boolean evento = tipoRepuestoController.modificarTipoProductoXid(id_tipo, nombreNuevo);
        JOptionPane.showMessageDialog(this, "Tipo de repuesto modificado correctamente");
        
        txt_tipoRepuesto.setText("");
        llenarCombo();
        llenarTabla();
        
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "No es posible conectar con base de datos SQL");
            }
        
        
        } else{
        
        JOptionPane.showMessageDialog(this, "Debe completar campos con datos no duplicados");
        
        }

        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
    int id_tipo = Integer.parseInt(combo_todoTipo.getSelectedItem().toString());
        try {
            TipoProducto.eliminarTipo(id_tipo);
            llenarCombo();
            llenarTabla();
            
            JOptionPane.showMessageDialog(this, "Tipo de Producto automotriz eliminado");
            
        } catch (Exception e) {
        }
    
    }//GEN-LAST:event_btn_eliminarActionPerformed


    
    public void llenarTabla(){
    tabla_tipoRepuesto.setModel(model);
    model.setRowCount(0);
    
        try {
       
       TipoRepuestoController tipoRepuestoController = new TipoRepuestoController();
       ArrayList <TipoProducto> listaTipo = tipoRepuestoController.listaTodosTipos();
       
            for (TipoProducto tipoproductoindex : listaTipo) {
                Object[] objeto = new Object[2];
                objeto[0]= tipoproductoindex.getTipoNombre();
                objeto[1]= tipoproductoindex.getId_tipo();
                int estado = tipoproductoindex.getEstado_tipo();
                
                if (estado == 1) {
                    
                    model.addRow(objeto);
                }
                
                
            }
    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No es posible conectar con base de datos SQL (package.VistaController.vistaTipoRepuesto.err)");
        }
    
    }
    
    
    public void llenarCombo(){
    
        combo_todoTipo.removeAllItems();
        try {
       
       TipoRepuestoController tipoRepuestoController = new TipoRepuestoController();
       ArrayList <TipoProducto> listaTipo = tipoRepuestoController.listaTodosTipos();
       
            for (TipoProducto ProductoIndex : listaTipo) {
               
                int estado = ProductoIndex.getEstado_tipo();
                
                if (estado == 1) {
                    
                    combo_todoTipo.addItem(String.valueOf(ProductoIndex.getId_tipo()));
                }
                
                
            }
       
        } catch (Exception e) {
        }
               
       
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> combo_todoTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabla_tipoRepuesto;
    private javax.swing.JTextField txt_tipoRepuesto;
    // End of variables declaration//GEN-END:variables
}
